# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &name longhorn
  namespace: longhorn-system
spec:
  interval: 10m
  releaseName: *name
  chart:
    spec:
      chart: *name
      version: 1.7.2
      sourceRef:
        kind: HelmRepository
        name: longhorn
        namespace: flux-system
  install:
    remediation:
      retries: &retries 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: *retries
  # https://longhorn.io/docs/1.7.2/advanced-resources/deploy/customizing-default-settings/#using-helm
  values:
    defaultSettings:
      defaultDataPath: "/var/lib/longhorn"
    ingress:
      enabled: true
      annotations:
        gethomepage.dev/enabled: "true"
        gethomepage.dev/description: "Cloud-native distributed storage built on and for Kubernetes."
        gethomepage.dev/group: Tools
        gethomepage.dev/icon: "https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/svg/longhorn.svg"
        gethomepage.dev/name: "Longhorn"
        gethomepage.dev/pod-selector: ""
        nginx.ingress.kubernetes.io/auth-url: |-
          http://ak-outpost-authentik-embedded-outpost.security.svc.cluster.local:9000/outpost.goauthentik.io/auth/nginx
        nginx.ingress.kubernetes.io/auth-response-headers: |-
          Set-Cookie,X-authentik-username,X-authentik-groups,X-authentik-email,X-authentik-name,X-authentik-uid
        nginx.ingress.kubernetes.io/auth-snippet: |-
          proxy_set_header X-Forwarded-Host $http_host;
        nginx.ingress.kubernetes.io/auth-signin: |-
          https://longhorn.${DOMAIN_PRIVATE}/outpost.goauthentik.io/start?rd=$scheme://$http_host$escaped_request_uri
      ingressClassName: nginx
      host: "longhorn.${DOMAIN_PRIVATE}"
      tls: true
