# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/postgresql.cnpg.io/databaserole_v1.json

apiVersion: postgresql.cnpg.io/v1
kind: DatabaseRole
metadata:
  name: pg-alpha-sure
spec:
  cluster:
    name: pg-alpha
  name: sure
  login: true
  passwordSecret:
    name: pg-alpha-sure
