# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json

apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name pg-alpha-sure
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: op
  target:
    name: *name
  data:
    - secretKey: username
      remoteRef:
        key: "dr75lclv7s7myznpqcymmgaz6e/username"
    - secretKey: password
      remoteRef:
        key: "dr75lclv7s7myznpqcymmgaz6e/credential"
