---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # NOTE: do not try to compulsively sort list alphabetically
  - "./flux.yaml"
  - "./cluster.yaml"
