# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &name spegel
  namespace: registry
spec:
  interval: 10m
  releaseName: *name
  chart:
    spec:
      chart: *name
      version: v0.0.29
      sourceRef:
        kind: HelmRepository
        name: *name
        namespace: flux-system
  install:
    remediation:
      retries: &retries 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: *retries
  values:
    spegel:
      containerdRegistryConfigPath: "/etc/cri/conf.d/hosts"

    serviceMonitor:
      enabled: true
