# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/core/secret_v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cluster-vars
  namespace: flux-system
stringData:
  DOMAIN_EXTERNAL: ENC[AES256_GCM,data:hIs0A6YBG3xc+dI=,iv:U70XzL5HF0RsuaAdNRD3orbO7p1pO8HVRGRc2hXB2eA=,tag:kv322BXEGYf/7KyPSeKdUw==,type:str]
  DOMAIN_INTERNAL: ENC[AES256_GCM,data:YDNLXuzigNPguVTSWA==,iv:nFCH/igOsAjlDsOwwlpA9s20hzMlo2fczx+pjwUjRV4=,tag:UWIm8i3hSi8YAlZksSNhrA==,type:str]
  EMAIL_CONTACT: ENC[AES256_GCM,data:zws1oJCxoQBgG+DGILL2,iv:3b4at8kXPkg8lKn9g3BsmPx9MNnfZr/HehG1Oxosg6w=,tag:IVgsc8R9Xs8RryCKABzCNQ==,type:str]
  EMAIL_PRIVATE: ENC[AES256_GCM,data:ER8OV3lOQLr7GhmGpwAzzB8u8yc46JZ6Fg==,iv:sZ+BIOsnzNIlUxgzRVQMAIuHPDOrQJJ5WLd63qyQ0Sc=,tag:kAueN5mVSAsCzp4GUpk8JQ==,type:str]
  ONEPASSWORD_VAULT: ENC[AES256_GCM,data:5uhj5cr0EP/Q2hpfWA==,iv:YR+c+EQuKElWM13yfsyeWLt5BLntg9uyyb4E9WmO2IU=,tag:JBu8Z3fchHkWyni2lpgxXQ==,type:str]
  SUBDOMAIN_IDP: ENC[AES256_GCM,data:tPkNrCSi,iv:7OrCCrvGbs71f/24jqzNNdKDWnO8dsVXawdQa/hDTQM=,tag:Lmne3xjHibDhWKBkbgUcyg==,type:str]
  SUBDOMAIN_NETBIRD_HCI: ENC[AES256_GCM,data:5DhzSOpP,iv:fAQXNtNelOQDWsAYxTGL+Wod9/NEsO/AmWBHhEqEg4w=,tag:2VXDdtyYmor/nbzSlY4XLw==,type:str]
  TAILNET_NAME: ENC[AES256_GCM,data:mO7ucpzsLwuehbTaBinqoKKGMRPBXA==,iv:y6I9WcnQLh8y7bBz6zKo7zazNyicjQUJ+4Fhx80WkYI=,tag:9C/t40bzruqZ4I+TkuhFLw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIMHlkUjl1S2tsQWt3YnVl
        bTVrUENVaGMzU3owMWJ1YmF6Z0RxWFgvV1FBCmtqaDVLT0lZVXlZSzU4eTNMSEcr
        OHg4OFJaVzF3cE4rdVFPcmdoZW01eEkKLS0tIHUxRUR1V3V0azlSdjZPWmdNK0Jx
        NDdwTWpqVGFhNWw1eExoSGdaWHV4QU0KNpCo9TndedaxA820LhV5/fucnT1r0zdS
        IJGUFltKNRUlJHYXxyBnxuE5Wlc+daEHw+EurtPyJwfvtJ3zIFcBXw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1avqzr4clyk00gzdrphyn560dtuh7t8r8a2qcmwx6trhgxf4qcyfs8n9al3
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-11T21:51:04Z"
  mac: ENC[AES256_GCM,data:2Y5vsRkwo/al2W2nbg0cj/xl3sGSt7xBLGWzDm9ajMg4CXcG/R9h48LjwMzIx2fbXZuEvyXyeVx/ehXXuAWWyiPtJJ/tEpLwX1U3uS//aLArPByb/a67FCC7NFsJrhGZHDWfyu/HLmYycEQIDwkhu2EQQQNk49JngHiuAtMZ2VA=,iv:HApNjOhzFY9l7mP958VioUI+hfAR4vmXV/KXuHvRV1c=,tag:eUEUm7UWB7M6lm7vqNzpJg==,type:str]
  mac_only_encrypted: true
  version: 3.13.2
