# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/master/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: github-key
  namespace: flux-system
stringData:
  username: ENC[AES256_GCM,data:CZcF,iv:O0tzvqlCT9mPCRoEeb13z7hWYElaEQcTqCevOy8tqwA=,tag:SP8cYA1ad0EUZC1ukpJG0A==,type:str]
  password: ENC[AES256_GCM,data:0EtFhTggnq8jcejjMZ/ic3ai55aLuySCEn/71/pRPn8hIwpe200Z3NQt744ztZnPN366rFaLauLOfF3F6Ejf91EureNXQLEAgbHrncOk6DY1oP2PpeSVg/yT97mU,iv:jYuHNHh6B3IerYYegi7++4NZ5s3G6uK3GBna/WTyCSA=,tag:smbm3N62M70M+z8ylEC4cQ==,type:str]
sops:
  age:
    - recipient: age1avqzr4clyk00gzdrphyn560dtuh7t8r8a2qcmwx6trhgxf4qcyfs8n9al3
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0SmR0d2kxSTJIUi9EUW5F
        Q1BieFNCc1ZwTjNjais5RGdRcmJ6ZFJjQTFVCkRoV2pEVGZlOXhHakU3UzB3NUts
        Ump1Q0JNSVZNR2psV2QyZ1ZPOGg1c0EKLS0tIG5YVnpZeG9MSWpkMVN5c1lmOVBz
        VU9nUEtRS3lDOTY4ODJYV3EzRzJaUm8KEFyUZC902PQNavnxgyn/MhuQ3Q7wbXhZ
        hXD5SXRoF7JureGRtwO8PBuruNuLt9bfuJ+Qu650P1DtbiU3wcaneA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-03T02:40:41Z"
  mac: ENC[AES256_GCM,data:oeeyNQBYqH0bTk+aMnopM3ZyxqJ8Umwx/2gNabx9n+wI38Wdw7Ledfra9mPxQ7zIs+iFB2jL+DHKFoD+PEeil+n9o2cYnK4G/DzGU+2bWfhXjsqstPBor+K/oYtkLyX2ITz7o+8nZaX7yv+yj4MoQVKyzyx4A/8JOAnWkZ3ul2E=,iv:gqlBG0r1LSQXpqkLaokaOY+07WRWJDn9vTjqCFVVrKI=,tag:oz4bxDH75VoZELQvZJVwAw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
