# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/core/secret_v1.json
apiVersion: v1
kind: Secret
metadata:
  name: github-key
  namespace: flux-system
stringData:
  username: ENC[AES256_GCM,data:pKJ7,iv:2IjKkedVbqYPMQ6/LF3HhhEroF/d9mucuMRe9Py+trQ=,tag:rXyWOkwL+C7El/Fk9Ecm/Q==,type:str]
  password: ENC[AES256_GCM,data:s7HxSJN7uzJKv64sgGUbgud+GYm52KjdeSpIvxFmFV7e/Qe6YB4Rmjfg+xlrlugsAQFGH0IEHMC2BrKL9TbS/uvr4z0rx/VvC78nkpla9fJp4w0vy+53jDSB5xAK,iv:XDOPmztEbZ0RwZZp3PLi96YcwwNFdp6sQ/SONWKvi7o=,tag:Kl77jyzEMv89dnXDpoS6tA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkWDcxa200YWtSR0VSK0Za
        UW1xMWtVN2ZtWmNBbUFLclRIYkdmSXVYUnpJCm91WjN1S0FPVm1QVjR5aDJ3RkpR
        eXVlNytEUGV4SzYzOWdvaXVuNncrcnMKLS0tIHlDQXlYdHExeFVYT1dDVDZHVTRk
        WklpdWpqeXpIU3ZtaDlkTEQvQUY0b28KfYCpdXgyICQFzyZvTACKcbI8X8JWAM1M
        DQz8OH9PiF5xK8ALe0CDEzQl+H8IFA7Cb3EoiNK/J1wo9HCcG70+zw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1avqzr4clyk00gzdrphyn560dtuh7t8r8a2qcmwx6trhgxf4qcyfs8n9al3
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-31T22:07:17Z"
  mac: ENC[AES256_GCM,data:IA2gb5cGrDHxuKNoUJnelZVRYy46HTMBLHD3OtWBZtiI2vXezVZjHtbNTIJa+UfgSYhzuOj7Ez/g9E0VedsaIdbuubfaZs/YOnSQIu9a30scjzNO4ZiKjEId9NdGEcAOnR622OtRh+Z+Y+M+gWgDkmkUxmTddEAL0lmzLqqI0sY=,iv:3eICFAgwuFu3FLZN62rccWPmroIfap+iq0U+HYzTrZQ=,tag:oa9KMOS+rd28RnBxVBulnQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
