# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/core/secret_v1.json
apiVersion: v1
kind: Secret
metadata:
  name: github-key
  namespace: flux-system
stringData:
  username: ENC[AES256_GCM,data:aRLX,iv:IdSDj9RIzq9zhm3FCYsZ70EmYd4p9RKdP0Ncst1FaEE=,tag:fwapQAXzro6RaEe8UkdVEA==,type:str]
  password: ENC[AES256_GCM,data:j402FjNWhKAUH51DuBQqWOWZKHnegDL5yoIg0PwIGOvGtzu3K5E5bV4Nv7mE8bdXEOIJ9BDtYRJ73Bt62jwNA8mmuVUzXmmSYEhO91Ao1BvVsO+0kiqJQ+cLd27v,iv:ghk1zQXM45kXvs66N4ZOBruUBEi7Z6U6kB/GXZDoN9Q=,tag:1gl1N+VhzHk827Xo/Y/+vA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnbmozVWJTOGwrQmRvcDZ5
        b05uUTgvUUFqYXFHSlh5c3hINmpEVDZXMWpjCjE2WE05VVpUemJrVktnclE3ci96
        TDkzUU9pVS9iQk9HVWRGdmVhQVZKYWMKLS0tIDRrNHJPc2ZXNm5mYkhiRy9UMXhX
        aUdWRXhPLy9qSkFydVpESVlmVCtFVnMK0mOqb2rzpnewdvCw8/ejkvyYJNdwYlhG
        lkJ01TP7yPvfBfmjrLZSYHNtbJusAbxjee6vh9eWqjTWq3f9jex0jg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1avqzr4clyk00gzdrphyn560dtuh7t8r8a2qcmwx6trhgxf4qcyfs8n9al3
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-30T16:19:51Z"
  mac: ENC[AES256_GCM,data:LG8WvRk+MAmxaZzpzxydTQSdJbhO0dUBHGG51XPMmk7VracKMzFMYVMj2Jg9GVS/X+y3Q1XvQiEzkOd8pcMkpV2hGO8uOQ5lWhajWcOf163+BUsEEK6R7IS4ib2Hgu+2ia/+isWoZmsoSVfOBrgGnksJFLP8hp5e+EGw/CfkOs0=,iv:XFBpoxdCVPDhxgMjpP3J5wbtkqY0hRZ4Gyg+8K9cuvE=,tag:sQcJtLN8U6JSCKBJeIko8A==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
