# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/core/secret_v1.json
apiVersion: v1
kind: Secret
metadata:
  name: homelab-vars
  namespace: flux-system
stringData:
  DOMAIN_PRIVATE: ENC[AES256_GCM,data:F6wpsJ99o5YwRA5UxQ==,iv:4EmBJNWblFckuYZ0o7pSPJUVrTzfXxehcsFnojJhFX8=,tag:yZkDE0uMXQY11emBogc7EA==,type:str]
  EMAIL_CONTACT: ENC[AES256_GCM,data:cptLtOuVfO5LW/dmRiEQ,iv:KhUiZTnnwOFFp15zk69tk4A1WZnG6COpMYzc5qMZVlE=,tag:git8WoSAbb96pwpARihxJw==,type:str]
  EMAIL_PRIVATE: ENC[AES256_GCM,data:Oas2cTzTQfohvS1+z+4mVf/J/fK7rXrkmA==,iv:JXRNDKi+QqoVV6qUOwmSJWZ9Ni6hZ9enxLNm6MnT4xE=,tag:42PMjT2aaYPbHsxOHk9xSg==,type:str]
  TAILNET_NAME: ENC[AES256_GCM,data:llutG82sZqSC8x2ly6Hq1/0T02FPag==,iv:TkWRQONoJv4+DmupsZFxC6Uxl2oHzdQBFOjm0sJ8cxw=,tag:3CuV7eM3azW3KF9L141yFw==,type:str]
sops:
  age:
    - recipient: age1avqzr4clyk00gzdrphyn560dtuh7t8r8a2qcmwx6trhgxf4qcyfs8n9al3
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBldUFyVDZPTnVZMkhYUURu
        NFk2SkVJdDFmRk1GUUI1b1B5ZS9ZS3VzWVQ4Cit1R0JlWHBEWVZ3eDRqS0JEeUxN
        T1JoZVljWis1WTlqelFkOGpWK3B2ZTgKLS0tIE8yK2dpVm5reW84L3JiWis5MmJI
        cm5ZWDJyWlNjVGNQWW80YktCaXNTZmsKbsx172sfOY7QADUVwdjrR07pzOZheKcC
        ykHV+eFXP0rwgwiopY7JNRtbar1d0kwVgJ7ltwA+DW1lv94mTnrrFw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-03T19:16:07Z"
  mac: ENC[AES256_GCM,data:Wct5rKVzPTykNDt6qJWMzC47Quzj9cPkWoOJSCjNg6CtWTJm167zV7zJEUS/0IKpNU6WjHFGXfRgmNNPaLGgCIQLrq6znNym5d5QOvcOdOR4e0PAgUzlSyI/qqgm00Ips2ALmVFhdwAwaDKNPNF/SCo6VJtpt0WvxnxrH6mFvQs=,iv:ZRdO/ICaLOOqcGvxfNc7aXMZq54HP9eGN0jE74kzRlY=,tag:2ypnq1h2qCnnC3xXBROzFQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
