apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &name authentik-oauth-grafana
  namespace: monitoring
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: &source bitwarden-secrets
  target:
    name: *name
  data:
    - secretKey: client_secret
      remoteRef:
        key: *source
        property: 092363d3-4b86-4c62-9c14-b22f00455296
