apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &name actions-runner-controller
  namespace: arc-runner
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: &source bitwarden-secrets
  target:
    name: *name
  data:
    - secretKey: ACTION_RUNNER_CONTROLLER_GITHUB_APP_ID
      remoteRef:
        key: *source
        property: b2f775b1-133c-40a0-86f6-b21d01682922
    - secretKey: ACTION_RUNNER_CONTROLLER_GITHUB_INSTALLATION_ID
      remoteRef:
        key: *source
        property: b7be4cfd-4366-4d0d-9b79-b21d0168692c
    - secretKey: ACTION_RUNNER_CONTROLLER_GITHUB_PRIVATE_KEY
      remoteRef:
        key: *source
        property: 32a0ea1c-3525-46f0-81f9-b21d01692002
