# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json

apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name grafana-oidc
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: op
  target:
    name: *name
  data:
    - secretKey: AUTH_CLIENT_ID
      remoteRef:
        key: "qwugshjcae6672sylsrxyhfp3q/username"
    - secretKey: AUTH_CLIENT_SECRET
      remoteRef:
        key: "qwugshjcae6672sylsrxyhfp3q/credential"
