# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/grafana.integreatly.org/grafana_v1beta1.json

apiVersion: grafana.integreatly.org/v1beta1
kind: Grafana
metadata:
  name: grafana
spec:
  # http://docs.grafana.org/installation/configuration/
  config:
    analytics:
      check_for_updates: "false"
    auth.generic_oauth:
      enabled: "true"
      name: "Huggins Cloud"
      allow_assign_grafana_admin: "true"
      api_url: "http://pocket-id.auth.svc.cluster.internal:1411/api/oidc/userinfo"
      auth_url: "https://${SUBDOMAIN_IDP}.${DOMAIN_INTERNAL}/authorize"
      auto_login: "true"
      client_id: "$${AUTH_CLIENT_ID}"
      client_secret: "$${AUTH_CLIENT_SECRET}"
      role_attribute_path: contains(groups, 'hci_admins') && 'GrafanaAdmin' || contains(groups, 'grafana_viewers') && 'Viewer' || 'None'
      role_attribute_strict: "true"
      scopes: "openid email profile groups"
      token_url: "http://pocket-id.auth.svc.cluster.internal:1411/api/oidc/token"
    paths:
      data: "/var/lib/grafana/"
      logs: "/var/log/grafana"
      plugins: "/var/lib/grafana/plugins"
      provisioning: "/etc/grafana/provisioning"
    log:
      mode: console
    grafana_net:
      url: https://grafana.net
    server:
      domain: "grafana.${DOMAIN_INTERNAL}"
      root_url: "https://grafana.${DOMAIN_INTERNAL}/"
  deployment:
    spec:
      strategy:
        type: Recreate
      template:
        spec:
          containers:
            - name: grafana
              envFrom:
                - secretRef:
                    name: "grafana-oidc"
                - secretRef:
                    name: "grafana"
              volumeMounts:
                - mountPath: "/etc/grafana/provisioning/dashboards"
                  name: provisioning-config
                - mountPath: "/var/lib/grafana/dashboards"
                  name: dashboards
            - name: grafana-sidecar
              image: "ghcr.io/kiwigrid/k8s-sidecar:2.1.4@sha256:0b56b3ef7efc0c47f87c2230c4dfdcfb5b4b7399132cd7daecede82f85d7e342"
              env:
                - name: LABEL
                  value: "grafana"
                - name: LABEL_VALUE
                  value: "dashboard"
                - name: FOLDER
                  value: "/var/lib/grafana/dashboards"
                - name: NAMESPACE
                  value: ALL
                - name: RESOURCE
                  value: configmap
              volumeMounts:
                - mountPath: "/var/lib/grafana/dashboards"
                  name: dashboards
          securityContext:
            fsGroup: 65534
            runAsGroup: 65534
            runAsNonRoot: true
            runAsUser: 65534
            seccompProfile:
              type: RuntimeDefault
          volumes:
            - name: grafana-data
              persistentVolumeClaim:
                claimName: grafana-pvc
            - name: dashboards
              emptyDir: {}
            - name: provisioning-config
              configMap:
                name: provisioning-config
  httpRoute:
    spec:
      parentRefs:
        - name: domain-internal
          namespace: gateway-system
          sectionName: default
      hostnames:
        - "grafana.${DOMAIN_INTERNAL}"
      rules:
        - matches:
            - path:
                type: PathPrefix
                value: /
          backendRefs:
            - name: grafana-service
              namespace: monitoring
              port: 3000
              weight: 1
  persistentVolumeClaim:
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 5Gi
      storageClassName: "longhorn"
