# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/core/secret_v1.json
apiVersion: v1
kind: Secret
metadata:
  name: grafana
stringData:
  GF_SECURITY_ADMIN_USER: ENC[AES256_GCM,data:ZxpmgsBmI1RaVcEQJA==,iv:oD1xzO5eQzCX7qpEHVo7bosJZoHCcnnSxTm4X67vfF8=,tag:I91saRrxc06DWS9P7uazmQ==,type:str]
  GF_SECURITY_ADMIN_PASSWORD: ENC[AES256_GCM,data:v/ygwvLl91CUVlRuKATs3cBL25ABT8/jRMxu1Yi52GJmAK7+ES+vEg==,iv:AbK64Xme5SracNu/JdOhohY+RaLhDXcoGM9/lea+OIg=,tag:neiGVutPb31zj8QCQrUj8w==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOelVrc2VOWkJUTWVGNlBF
        UTRJamRXRnJIRkV5UENuLzltUG9TcGVZc21vCmJKZUZjUHdQMklpdW04WDR6TUtG
        cWx0K0hPN1p1QlVSMjcwang2bFhKUTgKLS0tIGRNaXJLbkt3UXFpc3FFczBaeUwr
        dW9iRGNQcXF6b3pMTUhEUXFHZzdCTk0K4iyJohY0F7wvrvVJsJJi+CH3UN3ph5d+
        +PAtvEnoXwlLdAZVbEMiBRaX5g2HPep/Cbxw95OWCYFpX2Qs9sBQog==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1avqzr4clyk00gzdrphyn560dtuh7t8r8a2qcmwx6trhgxf4qcyfs8n9al3
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-17T01:05:54Z"
  mac: ENC[AES256_GCM,data:L/yjFtxj40vm3TA59hf3PDgwV34wFyakhP1eBcAgo8Ec0/IS9s7xmr+KsZAu1RILhMUkvmpTtFF4LT0mxbk5fXBzNTm1uzdlZWORVVBe56qPtvwQvtXichDgCzW57bpSkIsrgesgcDFAta07Qvn22wyrNgidlv7lR4YPhpqAl/I=,iv:sOjIzignTYQMAirBq17ftnoUSs2xB9SzblojRPfRnCk=,tag:D32w59zhS/gEaJIVlsPhJw==,type:str]
  mac_only_encrypted: true
  version: 3.13.2
