apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - "./namespace.yaml"
  ###
  - "./external-secrets/ks.yaml"
  - "./sm-operator/ks.yaml"
  - "./resources/bitwardensecrets.yaml"
  - "./resources/role.yaml"
  - "./resources/serviceaccount.yaml"
  - "./resources/rbac.yaml"
  - "./resources/clustersecretstore.yaml"
