# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/helmrelease-helm-v2.json

apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &name external-secrets
  namespace: *name
spec:
  interval: 1h
  releaseName: *name
  chart:
    spec:
      chart: *name
      version: 1.1.1
      sourceRef:
        kind: HelmRepository
        name: *name
        namespace: *name
  dependsOn:
    - name: tailscale-operator
      namespace: tailscale-system
  install:
    crds: CreateReplace
    remediation:
      retries: &retries 3
  upgrade:
    cleanupOnFail: true
    crds: CreateReplace
    remediation:
      retries: *retries
  valuesFrom:
    - kind: ConfigMap
      name: external-secrets-chart-values
