apiVersion: k8s.bitwarden.com/v1
kind: BitwardenSecret
metadata:
  name: &name bitwarden-secrets
  namespace: external-secrets
spec:
  organizationId: "21797038-89db-4d45-9bf3-b0f50187a295"
  secretName: *name
  authToken:
    secretName: bw-auth-token
    secretKey: BW_AUTH_TOKEN
