# yaml-language-server: $schema=https://raw.githubusercontent.com/cilium/cilium/refs/heads/main/install/kubernetes/cilium/values.schema.json
# https://docs.cilium.io/en/stable/

hubble:
  relay:
    enabled: true
  ui:
    enabled: true

ipam:
  mode: kubernetes

operator:
  replicas: 1
