# https://budimanjojo.github.io/talhelper/latest/
# yaml-language-server: $schema=https://raw.githubusercontent.com/budimanjojo/talhelper/refs/heads/master/pkg/config/schemas/talconfig.json

clusterName: &cluster darwin
endpoint: https://kube.darwin.internal:6443
additionalApiServerCertSans: &sans
  - "kube.darwin.internal"
  - "127.0.0.1"
additionalMachineCertSans: *sans
allowSchedulingOnControlPlanes: true

talosVersion: "v1.9.3"
kubernetesVersion: "v1.32.2"

nodes:
  - hostname: mini1
    controlPlane: true
    ipAddress: 10.0.1.21
    installDiskSelector:
      wwid: "naa.5002538500000000"
    nodeLabels:
      topology.kubernetes.io/region: homelab
      topology.kubernetes.io/zone: *cluster
    schematic:
      customization:
        systemExtensions:
          officialExtensions:
            - "siderolabs/intel-ucode"

patches:
  - |-
    machine:
      network:
        kubespan:
          enabled: false
        nameservers:
          - 10.0.1.1
          - 10.0.2.1
      systemDiskEncryption:
        ephemeral:
          provider: luks2
          keys:
            - nodeID: {}
              slot: 0
        state:
          provider: luks2
          keys:
            - nodeID: {}
              slot: 0
