# https://budimanjojo.github.io/talhelper/latest/
# yaml-language-server: $schema=https://raw.githubusercontent.com/budimanjojo/talhelper/refs/heads/master/pkg/config/schemas/talconfig.json

clusterName: &cluster darwin
endpoint: https://kube.darwin.internal:6443
additionalApiServerCertSans: &sans
  - "kube.darwin.internal"
  - "127.0.0.1"
additionalMachineCertSans: *sans
allowSchedulingOnControlPlanes: true

talosVersion: "v1.8.0"
kubernetesVersion: "v1.30.1"

nodes:
  - hostname: mini1
    controlPlane: true
    ipAddress: 10.0.1.21
    installDiskSelector:
      type: "SSD"
      wwid: "naa.5002538500000000"
    nodeLabels:
      topology.kubernetes.io/region: *cluster
    schematic:
      customization:
        systemExtensions:
          officialExtensions:
            - "siderolabs/intel-ucode"
patches:
  - |-
    machine:
      kubelet:
        extraArgs:
          rotate-server-certificates: true
      network:
        kubespan:
          enabled: true
      systemDiskEncryption:
        ephemeral:
          provider: luks2
          keys:
            - nodeID: {}
              slot: 0
        state:
          provider: luks2
          keys:
            - nodeID: {}
              slot: 0
