# https://budimanjojo.github.io/talhelper/latest/
# yaml-language-server: $schema=https://raw.githubusercontent.com/budimanjojo/talhelper/refs/heads/master/pkg/config/schemas/talconfig.json

clusterName: &cluster darwin
endpoint: https://kube.darwin.internal:6443
additionalApiServerCertSans: &sans
  - "kube.darwin.internal"
  - "127.0.0.1"
additionalMachineCertSans: *sans
allowSchedulingOnControlPlanes: true

talosVersion: "v1.9.4"
kubernetesVersion: "v1.32.2"

nodes:
  - hostname: mini1
    controlPlane: true
    ipAddress: 10.0.1.21
    installDiskSelector:
      wwid: "naa.5002538500000000"
    nodeLabels:
      topology.kubernetes.io/region: homelab
      topology.kubernetes.io/zone: *cluster
    machineDisks:
      - device: /dev/disk/by-id/ata-APPLE_HDD_HTS541010A9E662_J88000ESKD8XDB
        partitions:
          - mountpoint: "/var/lib/local-path-provisioner"
    schematic:
      customization:
        extraKernelArgs:
          - "talos.dashboard.disabled=1"
        systemExtensions:
          officialExtensions:
            - "siderolabs/i915"
            - "siderolabs/intel-ucode"
            - "siderolabs/iscsi-tools"
            - "siderolabs/util-linux-tools"
    patches:
      - |-
        cluster:
          network:
            cni:
              name: none
          proxy:
            disabled: true
        machine:
          kubelet:
            extraArgs:
              rotate-server-certificates: true
            extraMounts:
              - destination: "/var/lib/local-path-provisioner"
                type: bind
                source: "/var/lib/local-path-provisioner"
                options:
                  - bind
                  - rshared
                  - rw
          network:
            kubespan:
              enabled: false
            nameservers:
              - 10.0.1.1
              - 10.0.2.1
