# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app tailscale-operator
  namespace: flux-system
spec:
  targetNamespace: tailscale-system
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  path: ./kubernetes-flux/shared/tailscale-system/tailscale-operator/app
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: homelab
    namespace: flux-system
  interval: 1h
  retryInterval: 1m
  timeout: 5m
