# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/refs/heads/main/external-secrets.io/externalsecret_v1.json

apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name image-pull-atcr
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: kv2
  target:
    name: *name
    template:
      engineVersion: v2
      data:
        .dockerconfigjson: |
          {
            "auths": {
              "https://atcr.io": {
                "username": "huggins.io",
                "email": "kyle@huggins.io",
                "password": "{{ .registry-pass | toString }}",
                "auth": "{{ printf "%s:%s" "huggins.io" (.registry-pass | toString) | b64enc }}"
              }
            }
          }
data:
  - secretKey: registry-pass
    remoteRef:
      decodingStrategy: Base64
      key: "atproto/atcr-password"
