# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/common-5.0.1/charts/library/common/values.schema.json
# https://bjw-s-labs.github.io/helm-charts/docs/app-template/

defaultPodOptions:
  automountServiceAccountToken: false
  hostUsers: false
  imagePullSecrets:
    - name: image-pull-atcr
  securityContext:
    seccompProfile:
      type: RuntimeDefault
    fsGroup: 1000
controllers:
  app:
    enabled: true
    type: statefulset
    containers:
      app:
        image:
          repository: "atcr.io/tangled.org/knot"
          tag: "v1.14.1-alpha@sha256:ec8f86f35a8045591bf6111807658f5a3f156b727c9e26e6fbf378dd6a2975b7"
        securityContext:
          allowPrivilegeEscalation: true
          capabilities:
            drop:
              - ALL
            add:
              - SETUID
              - SETGID
        resources:
          requests:
            cpu: 10m
            memory: 64Mi
          limits:
            memory: 128Mi
        env:
          KNOT_REPO_SCAN_PATH: "/home/git/"
          KNOT_SERVER_DB_PATH: "/app/knotserver.db"
          KNOT_SERVER_HOSTNAME: "knot.huggins.dev"
          KNOT_SERVER_INTERNAL_LISTEN_ADDR: "127.0.0.1:5444"
          KNOT_SERVER_LISTEN_ADDR: "127.0.0.1:5555"
          KNOT_SERVER_OWNER: "did:plc:u3wyfpuwts2qoletvwlaon6v"
service:
  app:
    controller: app
    ports:
      http:
        port: 5555
  ssh:
    controller: app
    type: LoadBalancer
    annotations:
      lbipam.cilium.io/ips: "10.0.2.37"
    ports:
      ssh:
        port: 22
        targetPort: 22
route:
  app:
    hostnames:
      - "knot.${DOMAIN_PRIVATE}"
    parentRefs:
      - name: blade-internal
        namespace: gateway-system
        sectionName: default
    rules:
      - backendRefs:
          - identifier: app
            port: 5555
persistence:
  data:
    accessMode: ReadWriteOnce
    globalMounts:
      - path: "/app/"
        subPath: server
      - path: "/etc/ssh/keys/"
        subPath: ssh
      - path: "/home/git/"
        subPath: git
    size: 10Gi
    storageClass: longhorn
  tmp:
    type: emptyDir
