# yaml-language-server: $schema=https://raw.githubusercontent.com/hugginsio/CRDs-catalog/refs/heads/main/external-secrets.io/externalsecret_v1beta1.json

apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name sample-key
  namespace: default
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: kv2
  target:
    name: *name
  data:
    - secretKey: "user" # generated secret key
      remoteRef:
        decodingStrategy: Base64
        key: "proton-openvpn-user" # kv2 key
