# yaml-language-server: $schema=https://json.schemastore.org/kustomization

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - "./namespace.yaml"
  #
  - "./resources/externalsecret.yaml"
  - "./resources/clusterissuer.yaml"
  - "./resources/certificate.yaml"
  #
  - "./blocky/ks.yaml"
  - "./ingress-nginx/ks.yaml"
