# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json

apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app plex
  namespace: flux-system
spec:
  targetNamespace: media
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  path: ./kubernetes-flux/hyper/media/plex/app
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: homelab
    namespace: flux-system
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  dependsOn:
    # plex-files contains the media PVC
    - name: plex-files
