---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &name metallb
  namespace: network-system
spec:
  interval: 10m
  releaseName: *name
  chart:
    spec:
      chart: metallb
      version: 0.14.8
      sourceRef:
        kind: HelmRepository
        name: metallb
        namespace: flux-system
  install:
    crds: CreateReplace
    remediation:
      retries: &retries 3
  upgrade:
    cleanupOnFail: true
    crds: CreateReplace
    remediation:
      retries: *retries
