# https://pre-commit.com
# yaml-language-server: $schema=https://json.schemastore.org/pre-commit-config.json

repos:
  - repo: local
    hooks:
      - id: prevent-bruno-env
        name: Check for private Bruno env
        entry: prevent-bruno-env
        language: fail
        files: 'bruno/.env$'
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: check-merge-conflict
      - id: check-yaml
        args:
          - "--allow-multiple-documents"
      - id: end-of-file-fixer
      - id: pretty-format-json
        args:
          - "--autofix"
          - "--no-ensure-ascii"
          - "--no-sort-keys"
      - id: trailing-whitespace
