# yaml-language-server: $schema=https://json.schemastore.org/kustomization

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - "./helmrelease.yaml"
  ###
  - "./policies/container-resources-policy.yaml"
  - "./policies/trusted-repos-and-tags.yaml"
  - "./policies/unique-ingress-policy.yaml"
  - "./policies/user-group-psp.yaml"
configMapGenerator:
  - name: "kubewarden-values"
    files:
      - "./resources/values.yaml"
generatorOptions:
  disableNameSuffixHash: true
