apiVersion: generators.external-secrets.io/v1alpha1
kind: ClusterGenerator
metadata:
  name: password-gen
spec:
  kind: Password
  generator:
    passwordSpec:
      length: 24
      symbolCharacters: "~!@#$%^&*_+`-=|:?,."
      noUpper: false
      allowRepeat: false
