# https://external-secrets.io/latest/api/clustersecretstore/

apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: bitwarden-secrets
spec:
  provider:
    kubernetes:
      remoteNamespace: &namespace secrets-toolkit
      server:
        caProvider:
          type: ConfigMap
          name: kube-root-ca.crt
          namespace: *namespace
          key: ca.crt
      auth:
        serviceAccount:
          name: secrets-toolkit-controller
          namespace: *namespace
  conditions:
    - namespaceSelector:
        matchLabels:
          kube.huggins.io/eso: "allow"
