global:
  checkNewVersion: true

log:
  level: WARN

api:
  insecure: true
  dashboard: true

# enable ping so the `traefik healthcheck` works
ping: {}

providers:
  docker:
    exposedByDefault: false
    watch: true
    network: traefik-external
  file:
    fileName: /etc/traefik/traefik.yaml
    watch: true

entryPoints:
  web:
    address: :80
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true
  websecure:
    address: :443

serversTransport:
  insecureSkipVerify: true
