# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app homepage
  namespace: flux-system
spec:
  targetNamespace: homepage
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  path: ./kubernetes/hyperlab/namespaces/homepage/homepage/app
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: homelab
  interval: 10m
  retryInterval: 1m
  timeout: 5m
