# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json

apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name cloudflare-gateway
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: kv2
  target:
    name: *name
  data:
    - secretKey: ACCOUNT_ID
      remoteRef:
        decodingStrategy: Base64
        key: "cloudflare/account-id"
    - secretKey: TOKEN
      remoteRef:
        decodingStrategy: Base64
        key: "cloudflare/huggins.dev/gateway-token"
