# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/refs/heads/main/gateway.networking.k8s.io/gatewayclass_v1.json

apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: cloudflare
spec:
  controllerName: "github.com/pl4nty/cloudflare-kubernetes-gateway"
  parametersRef:
    group: ""
    kind: Secret
    namespace: gateway-system
    name: cloudflare-gateway
