# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &name crunchy-postgres-operator
  namespace: database
spec:
  interval: 10m
  releaseName: *name
  chart:
    spec:
      chart: pgo
      version: 5.7.1
      sourceRef:
        kind: HelmRepository
        name: crunchy-data
        namespace: flux-system
  install:
    remediation:
      retries: &retries 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: *retries
  values: {}
