# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json

apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name garage-admin-token
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: op
  target:
    name: *name
  data:
    - secretKey: admin-token
      remoteRef:
        key: "gnzzsxa2ow4ze7ervrg7t5o4ma/admin-token"
