# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json

apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name image-pull-atcr
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: kv2
  target:
    name: *name
    template:
      data:
        .dockerconfigjson: |
          {
            "auths": {
              "https://atcr.io": {
                "username": "huggins.io",
                "email": "kyle@huggins.io",
                "password": "{{ .registryPass | toString }}",
                "auth": "{{ printf "%s:%s" "huggins.io" (.registryPass | toString) | b64enc }}"
              }
            }
          }
  data:
    - secretKey: registryPass
      remoteRef:
        decodingStrategy: Base64
        key: "atproto/atcr-password"
