# Compose file for the Portainer Agent

name: "portainer_agent"
services:
  portainer_agent:
    image: "portainer/agent:2.16.2"
    container_name: "portainer_agent"
    restart: "unless-stopped"
    logging:
      driver: "local"
      options:
        max-file: "3"
        max-size: "5m"
    ports:
      - "9001:9001"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "/etc/localtime:/etc/localtime:ro"
      - "/var/lib/docker/volumes:/var/lib/docker/volumes"
