# Compose file for Autoheal

name: "autoheal"
services:
  autoheal:
    image: "willfarrell/autoheal:1.2.0"
    container_name: "autoheal"
    restart: unless-stopped
    logging:
      driver: "local"
      options:
        max-file: "3"
        max-size: "5m"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "/etc/localtime:/etc/localtime:ro"
    environment:
      - "AUTOHEAL_CONTAINER_LABEL=all"
      - "AUTOHEAL_INTERVAL=30"
      - "AUTOHEAL_START_PERIOD=30"
