# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/helmrelease-helm-v2.json

apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app kyverno-pod-security
  namespace: &ns kyverno-system
spec:
  interval: 1h
  releaseName: *app
  chart:
    spec:
      chart: kyverno-policies
      version: 3.6.1
      sourceRef:
        kind: HelmRepository
        name: kyverno
        namespace: *ns
  install:
    crds: CreateReplace
    remediation:
      retries: &retries 3
  upgrade:
    cleanupOnFail: true
    crds: CreateReplace
    remediation:
      retries: *retries
  valuesFrom:
    - kind: ConfigMap
      name: kyverno-pod-security-chart-values
