# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrepository-source-v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: gh-arc
  namespace: flux-system
spec:
  interval: 1h
  type: oci
  url: "oci://ghcr.io/actions/actions-runner-controller-charts"
