---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &name authentik-postgres
  namespace: security
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: database-secrets
  target:
    name: *name
  data:
    - secretKey: AUTHENTIK_POSTGRESQL__HOST
      remoteRef:
        key: &ppa postgres-pguser-authentik
        property: host
    - secretKey: AUTHENTIK_POSTGRESQL__NAME
      remoteRef:
        key: *ppa
        property: dbname
    - secretKey: AUTHENTIK_POSTGRESQL__USER
      remoteRef:
        key: *ppa
        property: user
    - secretKey: AUTHENTIK_POSTGRESQL__PORT
      remoteRef:
        key: *ppa
        property: port
    - secretKey: AUTHENTIK_POSTGRESQL__PASSWORD
      remoteRef:
        key: *ppa
        property: password
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &name authentik-misc
  namespace: security
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: &source bitwarden-secrets
  target:
    name: *name
  data:
    - secretKey: AUTHENTIK_SECRET_KEY
      remoteRef:
        key: *source
        property: beefd92a-0908-40e0-ba8a-b21c016a3baf
