# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/common-5.0.1/charts/library/common/values.schema.json
# https://bjw-s-labs.github.io/helm-charts/docs/app-template/

defaultPodOptions:
  automountServiceAccountToken: false
  hostUsers: false
controllers:
  app:
    enabled: true
    type: statefulset
    containers:
      app:
        image:
          repository: "lscr.io/linuxserver/calibre"
          tag: "9.8.0@sha256:02f1bfe7194e11c56958a2181dd0526e4312cd3d843e9f0ea0e1f60e4aa1d698"
        resources:
          requests:
            cpu: 100m
            memory: 1024Mi
          limits:
            memory: 2048Mi
        env:
          TITLE: Calibre
          TZ: ${TIMEZONE}
service:
  app:
    controller: app
    ports:
      http:
        port: 8080
  opds:
    controller: app
    ports:
      http:
        port: 8081
route:
  app:
    hostnames:
      - "{{ .Release.Name }}.${DOMAIN_INTERNAL}"
    parentRefs:
      - name: blade-internal
        namespace: gateway-system
        sectionName: default
    rules:
      - backendRefs:
          - identifier: app
persistence:
  config:
    accessMode: ReadWriteOnce
    size: 15Gi
    storageClass: longhorn
  tmp:
    type: emptyDir
