# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/source.toolkit.fluxcd.io/ocirepository_v1.json

apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: garage-operator
spec:
  interval: 99h
  url: "oci://ghcr.io/rajsinghtech/charts/garage-operator"
  ref:
    tag: 0.7.8
    digest: sha256:c7e386a89885f58e62a9589361b9c0243523f11625bcf52cf3bf43cdede0d580
