# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/master/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    DOMAIN_PRIVATE: ENC[AES256_GCM,data:yvI+8yBqyVpuEO+t6Q==,iv:8al/V7d7qcvKpU8nDH8+q0yaj5NwGaI9vk72ECJ9/rk=,tag:Z9IycDZa4sujLRQsF9ocyw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1avqzr4clyk00gzdrphyn560dtuh7t8r8a2qcmwx6trhgxf4qcyfs8n9al3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzZHN2KzRiNkRDQUp4VWl3
            N1ZDWkswampSQUdnd1lJTzhnNmNqbWNRRnhjCjJFeVZ2NnZFOFZOcG11WE4vRnk4
            NWgyb3FzQi9idjRIeFJ5MWtRRXFIcUUKLS0tICtpZW1pR2tKcjRpWXdwSXRwQ2V3
            bzZuRDFtQ2x3V3IxZnBjckIwenVxR0UKQRGU1TWiSE1egvke25TsXZy1TswTWBNQ
            QAGNoNj2GjtZDkShVXbnDkQO/GcRYUefL6r4xRkruXli5HkUA8nuzw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-30T00:28:28Z"
    mac: ENC[AES256_GCM,data:c3G4MkBMG+HGsYlQY8vnZMI44dOFda/T7pEZfwrJ6IOy0KtmUY98Z6iV/DsRistzJRmGy53tpvbi5EK2CYEJFIm9OhGgTfuES8hTiVkliklvIJUt/RxvirPApTkJMQH30rLU+no7T92goJ0X3U74izVkYuCpASnu09FYVgXmIPY=,iv:+EAQsKN2u+Pxtnxc/mmHvZP2UadpWnOJHRCzKBcn98s=,tag:Z0BSrwnI4JfAVOEBP0WUxg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.9.0
