# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json

apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name pocket-id-encryption-key
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: op
  target:
    name: *name
  data:
    - secretKey: ENCRYPTION_KEY
      remoteRef:
        key: "z64i7rxdmm4an4bj2paqof6bci/credential"
