# Compose file for MeTube

name: "metube"
services:
  metube:
    image: "ghcr.io/alexta69/metube:2024-04-12"
    container_name: "metube"
    restart: "unless-stopped"
    networks:
      - "traefik-external"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "${PATH_PARENT}/Pending/metube:/downloads"
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik-external"
      - "traefik.http.routers.metube.rule=Host(`metube.${DOMAIN_NAME}`)"
      - "traefik.http.services.metube.loadbalancer.server.port=8081"
      - "traefik.http.routers.metube.entrypoints=websecure"
      - "traefik.http.routers.metube.tls=true"
      - "homepage.group=Applications"
      - "homepage.name=MeTube"
      - "homepage.icon=https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/youtubedl.png"
      - "homepage.href=https://metube.${DOMAIN_NAME}"
      - "homepage.description=Music downloader for YouTube and more."
networks:
  traefik-external:
    external: true
