apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  namespace: kube-system
spec:
  acme:
    email: "${EMAIL_CONTACT}"
    server: "https://acme-v02.api.letsencrypt.org/directory"
    privateKeySecretRef:
      name: letsencrypt-prod-account-key
    solvers:
      - dns01:
          cloudflare:
            email: "${EMAIL_PRIVATE}"
            apiTokenSecretRef:
              name: cloudflare-api-key
              key: api-key
        selector:
          dnsZones:
            - "${DOMAIN_PRIVATE}"
