# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json

apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name files-oidc
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: op
  target:
    name: *name
  data:
    - secretKey: FILEBROWSER_OIDC_CLIENT_ID
      remoteRef:
        key: "ay7kcpzgj752bth3r35pnw44gq/username"
    - secretKey: FILEBROWSER_OIDC_CLIENT_SECRET
      remoteRef:
        key: "ay7kcpzgj752bth3r35pnw44gq/credential"
