# Compose file for Pi-hole

version: "3.9"
services:
  pi_hole:
    image: "pihole/pihole:2022.11.1"
    container_name: "pi_hole"
    hostname: "pi_hole-${DOCKER_HOSTNAME}"
    restart: unless-stopped
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "83:80/tcp"
    dns:
      - "127.0.0.1"
      - "1.1.1.1"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/home/${USERNAME}/homelab-sync/pi_hole-${DOCKER_HOSTNAME}/config:/etc/pihole"
      - "/home/${USERNAME}/homelab-sync/pi_hole-${DOCKER_HOSTNAME}/dnsmasq.d:/etc/dnsmasq.d"
    environment:
      - "TZ=America/Chicago"
      - "FTLCONF_REPLY_ADDR4=${IP_ADDRESS}"
      - "WEBPASSWORD=${PASSWORD}"
      - "PIHOLE_DNS_=1.1.1.1;1.0.0.1;2606:4700:4700::1111;2606:4700:4700::1001"
      - "WEBTHEME=default-auto"
      - "DNSMASQ_LISTENING=all"
    labels:
      - "homepage.group=Networking"
      - "homepage.name=Pi-hole (${DOCKER_HOSTNAME})"
      - "homepage.icon=https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/pihole.png"
      - "homepage.href=http://${IP_ADDRESS}:83/admin"
      - "homepage.description=A black hole for internet ads."
      - "homepage.widget.type=pihole"
      - "homepage.widget.url=http://${IP_ADDRESS}:83"
