# https://budimanjojo.github.io/talhelper/latest/
# yaml-language-server: $schema=https://raw.githubusercontent.com/budimanjojo/talhelper/refs/tags/v3.1.5/pkg/config/schemas/talconfig.json

clusterName: mini
endpoint: https://kube.mini.lab.home.arpa:6443
additionalApiServerCertSans: &sans
  - "kube.mini.lab.home.arpa"
allowSchedulingOnControlPlanes: true

talosVersion: "v1.13.0"
kubernetesVersion: "v1.36.0"

nodes:
  - hostname: mini1
    certSANs: *sans
    controlPlane: true
    ipAddress: 10.0.2.21
    nameservers:
      - 10.0.2.1
    installDiskSelector:
      wwid: "naa.5001b444a8fcea74"
    nodeLabels:
      topology.kubernetes.io/instance-type: old
      topology.kubernetes.io/region: arkansas
    userVolumes:
      - name: data
        provisioning:
          diskSelector:
            match: disk.wwid == "naa.500a0751e8ab55ad"
          grow: true
          minSize: 30GiB
        filesystem:
          type: xfs
        encryption:
          # NOTE: this is not an incorrect type, despite what the schema says
          provider: luks2
          keys:
            - slot: 0
              static:
                passphrase: ${ENCRYPTION_PASSPHRASE}
    schematic:
      customization:
        extraKernelArgs:
          - "talos.dashboard.disabled=1"
        systemExtensions:
          officialExtensions:
            - "siderolabs/intel-ucode" # Intel microcode
            - "siderolabs/util-linux-tools" # Selection of Linux utils
    patches:
      - |-
        cluster:
          apiServer:
            admissionControl:
              - name: PodSecurity
                configuration:
                  apiVersion: pod-security.admission.config.k8s.io/v1alpha1
                  defaults:
                    audit: privileged
                    audit-version: latest
                    enforce: privileged
                    enforce-version: latest
                    warn: restricted
                    warn-version: latest
                  exemptions:
                    namespaces: []
                    runtimeClasses: []
                    usernames: []
                  kind: PodSecurityConfiguration
            extraArgs: # https://kubernetes.io/docs/reference/command-line-tools-reference/kube-apiserver/
              max-mutating-requests-inflight: "100"
              max-requests-inflight: "200"
              watch-cache-sizes: ""
            resources:
              requests:
                cpu: 200m
                memory: 512Mi
              limits:
                memory: 1024Mi
          controllerManager:
            extraArgs: # https://kubernetes.io/docs/reference/command-line-tools-reference/kube-controller-manager/
              concurrent-deployment-syncs: "3"
              concurrent-replicaset-syncs: "3"
              kube-api-burst: "20"
              kube-api-qps: "15"
          discovery:
            enabled: false
          etcd:
            extraArgs: # https://etcd.io/docs/v3.6/op-guide/configuration/
              auto-compaction-mode: periodic
              auto-compaction-retention: 1h
              snapshot-count: "10000"
          network:
            cni:
              # NOTE: modify this for temporary clusters
              name: none
          proxy:
            # NOTE: modify this for temporary clusters
            disabled: true
        machine:
          features:
            kubernetesTalosAPIAccess:
              allowedKubernetesNamespaces:
                - "system-upgrade"
              allowedRoles:
                - "os:admin"
              enabled: true
          kubelet:
            extraArgs:
              rotate-server-certificates: true
          systemDiskEncryption:
            ephemeral:
              provider: luks2
              keys:
                - static:
                    passphrase: ${ENCRYPTION_PASSPHRASE}
                  slot: 0
          network:
            kubespan:
              enabled: false
          sysctls:
            user.max_user_namespaces: "11255"
