# https://external-secrets.io/latest/api/clustersecretstore/
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/clustersecretstore_v1.json

apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: op
spec:
  provider:
    onepasswordSDK:
      vault: "${ONEPASSWORD_VAULT}"
      auth:
        serviceAccountSecretRef:
          name: op-token
          namespace: secrets-system
          key: token
      integrationInfo:
        name: "${CLUSTER_NAME}"
  conditions:
    - namespaceSelector:
        matchLabels:
          secrets.huggins.dev/op: enable
