# https://0xerr0r.github.io/blocky/latest/configuration/

bootstrapDns:
  - "1.1.1.1"
  - "1.0.0.1"
upstreams:
  groups:
    default:
      - "https://dns.cloudflare.com/dns-query"
      - "https://1.1.1.1/dns-query"
      - "https://1.0.0.1/dns-query"
      - "https://dns.google/dns-query"
      - "1.1.1.1"
      - "1.0.0.1"
  init:
    strategy: failOnError
  strategy: strict
blocking:
  denylists:
    ads:
      # https://github.com/hagezi/dns-blocklists
      - "https://cdn.jsdelivr.net/gh/hagezi/dns-blocklists@latest/hosts/pro.txt"
      - "https://cdn.jsdelivr.net/gh/hagezi/dns-blocklists@latest/hosts/tif.txt"
      - "https://cdn.jsdelivr.net/gh/hagezi/dns-blocklists@latest/wildcard/anti.piracy-onlydomains.txt"
      - "https://cdn.jsdelivr.net/gh/hagezi/dns-blocklists@latest/wildcard/popupads.txt"
    dns:
      # https://github.com/hagezi/dns-blocklists
      - "https://cdn.jsdelivr.net/gh/hagezi/dns-blocklists@latest/wildcard/doh-vpn-proxy-bypass.txt"
    native:
      # https://github.com/hagezi/dns-blocklists?tab=readme-ov-file#calling-native-tracker---broadband-tracker-of-devices-services-and-operating-systems-
      - "https://cdn.jsdelivr.net/gh/hagezi/dns-blocklists@latest/hosts/native.amazon.txt"
      - "https://cdn.jsdelivr.net/gh/hagezi/dns-blocklists@latest/hosts/native.apple.txt"
      - "https://cdn.jsdelivr.net/gh/hagezi/dns-blocklists@latest/hosts/native.tiktok.txt"
      - "https://cdn.jsdelivr.net/gh/hagezi/dns-blocklists@latest/hosts/native.winoffice.txt"
  clientGroupsBlock:
    default:
      - ads
      - dns
      - native
customDNS:
  mapping:
    ${DOMAIN_PRIVATE}: 10.0.1.10
    kube.hyperlab.internal: 10.0.1.11,10.0.1.12,10.0.1.13
ports:
  dns: 53
  http: 4000
prometheus:
  enable: true
  path: "/metrics"
redis:
  address: "redis.database.svc.cluster.local:6379"
