# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/helm.toolkit.fluxcd.io/helmrelease_v2.json

apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &name cert-manager
spec:
  interval: 3h
  releaseName: *name
  chart:
    spec:
      chart: *name
      version: v1.21.0
      sourceRef:
        kind: HelmRepository
        name: jetstack
        namespace: flux-system
  install:
    remediation:
      retries: &retries 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: *retries
  valuesFrom:
    - kind: ConfigMap
      name: cert-manager-chart-values
