# Compose file for Microsoft SQL Server

name: mssql_server
services:
  mssql_server:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    container_name: "mssql_server"
    restart: unless-stopped
    logging:
      driver: "local"
      options:
        max-file: "3"
        max-size: "5m"
    ports:
      - "1433:1433"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "mssql_server:/var/opt/mssql"
    environment:
      - "ACCEPT_EULA=Y"
      - "MSSQL_SA_PASSWORD=${PASSWORD}"
volumes:
  mssql_server:
