# Compose file for Microsoft SQL Server

name: mssql_server
services:
  mssql_server:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    container_name: "mssql_server"
    restart: unless-stopped
    networks:
      - "traefik-external"
    logging:
      driver: "local"
      options:
        max-file: "3"
        max-size: "5m"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "mssql_server:/var/opt/mssql"
    environment:
      - "ACCEPT_EULA=Y"
      - "MSSQL_SA_PASSWORD=${PASSWORD}"
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik-external"
      - "traefik.http.routers.mssql.rule=Host(`mssql.${DOMAIN_NAME}`)"
      - "traefik.http.services.mssql.loadbalancer.server.port=1433"
      - "traefik.http.routers.mssql.entrypoints=mssql"
      - "traefik.http.routers.mssql.tls=true"
networks:
  traefik-external:
    external: true
