# yaml-language-server: $schema=https://raw.githubusercontent.com/cert-manager/cert-manager/refs/heads/master/deploy/charts/cert-manager/values.schema.json

clusterResourceNamespace: "cert-manager"

crds:
  enabled: true
  keep: true

extraArgs:
  - "--dns01-recursive-nameservers-only"
  - "--dns01-recursive-nameservers=1.1.1.1:53,1.0.0.1:53"

prometheus:
  servicemonitor:
    enabled: true
