---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app external-secrets
  namespace: flux-system
spec:
  targetNamespace: external-secrets
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  path: ./kubernetes/defaults/external-secrets/external-secrets/app
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: homelab
  interval: 10m
  retryInterval: 1m
  timeout: 5m
