# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/app-template-3.4.0/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json

apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &name gha-runner-scale-set
  namespace: arc-runner
spec:
  interval: 10m
  releaseName: *name
  chart:
    spec:
      chart: gha-runner-scale-set
      version: 0.9.3
      sourceRef:
        kind: HelmRepository
        name: gh-arc
        namespace: flux-system
  install:
    remediation:
      retries: &retries 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: *retries
  values:
    containerMode:
      type: dind
    controllerServiceAccount:
      name: gha-runner-scale-set-controller
      namespace: arc-runner
    maxRunners: 5
    minRunners: 0
    nameOverride: *name
    runnerScaleSetName: arc-hyperlab
    template:
      spec:
        containers:
          - name: runner
            image: ghcr.io/actions/actions-runner:2.320.0@sha256:8de989a63c2dad8aeb7c44b70f86189d148f887cbd917ecbe83879df54bf6590
            command: ["/home/runner/run.sh"]
    githubConfigUrl: "https://github.com/hugginsio/homelab"
  valuesFrom:
    - kind: Secret
      name: &secret actions-runner-controller
      valuesKey: ACTION_RUNNER_CONTROLLER_GITHUB_APP_ID
      targetPath: githubConfigSecret.github_app_id
    - kind: Secret
      name: *secret
      valuesKey: ACTION_RUNNER_CONTROLLER_GITHUB_INSTALLATION_ID
      targetPath: githubConfigSecret.github_app_installation_id
    - kind: Secret
      name: *secret
      valuesKey: ACTION_RUNNER_CONTROLLER_GITHUB_PRIVATE_KEY
      targetPath: githubConfigSecret.github_app_private_key
