---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - "./helmrelease.yaml"
  - "./resources/connector.yaml"
configMapGenerator:
  - name: tailscale-operator-chart-values
    files:
      - "./resources/values.yaml"
configurations:
  - "./configuration-configmap.yaml"
