---
# https://helmfile.readthedocs.io/en/stable/
# yaml-language-server: $schema=https://json.schemastore.org/helmfile.json

helmDefaults:
  wait: true
  waitForJobs: true
  timeout: 300
  force: true

repositories:
  - name: prometheus-community
    url: "https://prometheus-community.github.io/helm-charts"
  - name: postfinance
    url: "https://postfinance.github.io/kubelet-csr-approver"
  - name: metrics-server
    url: "https://kubernetes-sigs.github.io/metrics-server/"
  - name: bitwarden-sm
    url: "https://charts.bitwarden.com/"
  - name: external-secrets-charts
    url: "https://charts.external-secrets.io"

releases:
  - name: kubelet-csr-approver
    namespace: kube-system
    chart: "postfinance/kubelet-csr-approver"
    version: 1.2.3
  - name: prometheus-operator-crds
    namespace: monitoring
    chart: "prometheus-community/prometheus-operator-crds"
    version: 15.0.0
    needs:
      - "kube-system/kubelet-csr-approver"
  - name: metrics-server
    namespace: kube-system
    chart: "metrics-server/metrics-server"
    version: 3.12.2
    needs:
      - "kube-system/kubelet-csr-approver"
  - name: sm-operator
    namespace: secrets-toolkit
    chart: "bitwarden-sm/sm-operator"
    version: 0.1.0-Beta
    needs:
      - "kube-system/kubelet-csr-approver"
  - name: external-secrets
    namespace: secrets-toolkit
    chart: "external-secrets-charts/external-secrets"
    version: 0.10.4
    needs:
      - "kube-system/kubelet-csr-approver"
      - "secrets-toolkit/sm-operator"
