---
# https://helmfile.readthedocs.io/en/stable/
# yaml-language-server: $schema=https://json.schemastore.org/helmfile.json

helmDefaults:
  wait: true
  waitForJobs: true
  timeout: 300
  force: true

repositories:
  - name: cilium
    url: "https://helm.cilium.io"

releases:
  - name: cilium
    namespace: kube-system
    chart: "cilium/cilium"
    version: 1.16.2
    values:
      - "kube-system/cilium/app/resources/values.yaml"
