---
# https://helmfile.readthedocs.io/en/stable/
# yaml-language-server: $schema=https://json.schemastore.org/helmfile.json

helmDefaults:
  wait: true
  waitForJobs: true
  timeout: 300
  force: true

repositories:
  - name: bitwarden-sm
    url: "https://charts.bitwarden.com/"
  - name: prometheus-community
    url: "https://prometheus-community.github.io/helm-charts"
  - name: postfinance
    url: "https://postfinance.github.io/kubelet-csr-approver"
  - name: metrics-server
    url: "https://kubernetes-sigs.github.io/metrics-server/"
  - name: jetstack
    url: "https://charts.jetstack.io"

releases:
  # TODO: prometheus
  - name: prometheus-operator-crds
    namespace: monitoring
    chart: "prometheus-community/prometheus-operator-crds"
    version: 14.0.0
  - name: kubelet-csr-approver
    namespace: kube-system
    chart: "postfinance/kubelet-csr-approver"
    version: 1.2.2
  - name: metrics-server
    namespace: kube-system
    chart: "metrics-server/metrics-server"
    version: 3.12.1
    needs:
      - "kube-system/kubelet-csr-approver"
  - name: sm-operator
    namespace: sm-operator-system
    chart: "bitwarden-sm/sm-operator"
    version: 0.1.0-Beta
