---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: charts
  namespace: flux-system
spec:
  dependsOn:
    - name: namespaces
  interval: 1m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./kubernetes/charts
  prune: true
