---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: infra
  namespace: flux-system
spec:
  dependsOn:
    - name: crds
  interval: 1m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./kubernetes/infra
  prune: true
