# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/app-template-3.4.0/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &name actual-budget
  namespace: default
spec:
  interval: 10m
  releaseName: *name
  chart:
    spec:
      chart: app-template
      version: 3.4.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: &retries 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: *retries
  values:
    controllers:
      actual:
        enabled: true
        type: deployment
        containers:
          app:
            image:
              repository: "ghcr.io/actualbudget/actual-server"
              tag: "24.10.1"
            env:
              ACTUAL_PORT: &httpPort 5006
            resources:
              requests:
                cpu: 10m
                memory: 128Mi
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    port: *httpPort
                  initialDelaySeconds: 0
    ingress:
      app:
        enabled: true
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/description: "A local-first personal finance application."
          gethomepage.dev/group: Applications
          gethomepage.dev/icon: "https://cdn.jsdelivr.net/gh/selfhst/icons/svg/actual-budget.svg"
          gethomepage.dev/name: "Actual Budget"
          gethomepage.dev/pod-selector: ""
        hosts:
          - host: &host "actual.${DOMAIN_PRIVATE}"
            paths:
              - path: "/"
                pathType: Prefix
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - *host
    persistence:
      data:
        enabled: true
        existingClaim: actual-budget
    service:
      app:
        controller: actual
        ports:
          http:
            port: *httpPort
