# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/app-template-3.4.0/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json

apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &name prometheus-operator-crds
  namespace: monitoring
spec:
  interval: 10m
  releaseName: *name
  chart:
    spec:
      chart: prometheus-operator-crds
      version: 15.0.0
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
  install:
    crds: CreateReplace
    remediation:
      retries: &retries 3
  upgrade:
    cleanupOnFail: true
    crds: CreateReplace
    remediation:
      retries: *retries
  values: {}
