# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/common-5.1.0/charts/library/common/values.schema.json
# https://bjw-s-labs.github.io/helm-charts/docs/app-template/

defaultPodOptions:
  affinity:
    podAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchLabels:
              app.kubernetes.io/name: metube
          topologyKey: "kubernetes.io/hostname"
  automountServiceAccountToken: false
  hostUsers: false
  securityContext:
    fsGroup: 65534
    fsGroupChangePolicy: OnRootMismatch
    runAsGroup: 65534
    runAsNonRoot: true
    runAsUser: 65534
    seccompProfile:
      type: RuntimeDefault

controllers:
  app:
    enabled: true
    type: statefulset
    containers:
      app:
        image:
          repository: "ghcr.io/alexta69/metube"
          tag: "2026.08.28@sha256:397778fccf13d83adf9325fe813b260617a082d1772aff6d678c5b9256dd01fb"
        securityContext: &sc
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
          readOnlyRootFilesystem: true
        resources:
          requests:
            cpu: 200m
            memory: 512Mi
          limits:
            memory: 1Gi
        env:
          CLEAR_COMPLETED_AFTER: "28800"
          DELETE_FILE_ON_TRASHCAN: "true"
          TEMP_DIR: "/tmp"
          TZ: "${TIMEZONE}"
  cleanup:
    enabled: false
    type: cronjob
    cronjob:
      backoffLimit: 6
      concurrencyPolicy: Forbid
      failedJobsHistory: 3
      schedule: "0 */1 * * *"
      startingDeadlineSeconds: 30
      successfulJobsHistory: 1
      suspend: false
    annotations:
      kubernetes.io/description: "Deletes downloaded files that are more than an hour old."
    containers:
      app:
        image:
          repository: "docker.io/library/busybox"
          tag: 1.38.0@sha256:dc2d74b28e4cf8984fa52af1f39bc7c3d9c73760b41a74d629f5d11b1ab28616
        command: ["sh", "-c", "find /downloads -type f -mmin +60"]
        securityContext: *sc
        resources:
          requests:
            cpu: 10m
            memory: 16Mi
          limits:
            memory: 32Mi

service:
  app:
    controller: app
    ports:
      http:
        port: &port 8081

route:
  app:
    hostnames:
      - "{{ .Release.Name }}.${DOMAIN_INTERNAL}"
    parentRefs:
      - name: domain-internal
        namespace: gateway-system
        sectionName: default
    rules:
      - backendRefs:
          - identifier: app
            port: *port

persistence:
  downloads:
    type: persistentVolumeClaim
    accessMode: ReadWriteOnce
    size: 10Gi
    storageClass: nonreplicated
  tmp:
    type: emptyDir
