# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json

apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app system-upgrade-resources
  namespace: flux-system
spec:
  targetNamespace: system-upgrade
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  path: ./kubernetes-flux/mini/system-upgrade/resources/resources
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: homelab
    namespace: flux-system
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  dependsOn:
    - name: system-upgrade-tuppr
