# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/helmrelease-helm-v2.json

apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &name cilium
  namespace: kube-system
spec:
  interval: 1h
  releaseName: *name
  chart:
    spec:
      chart: *name
      version: 1.18.6
      sourceRef:
        kind: HelmRepository
        name: cilium
        namespace: kube-system
  install:
    crds: CreateReplace
    remediation:
      retries: &retries 3
  upgrade:
    cleanupOnFail: true
    crds: CreateReplace
    remediation:
      retries: *retries
  valuesFrom:
    - kind: ConfigMap
      name: cilium-chart-values
