# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json

apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name navidrome-oidc
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: op
  target:
    name: *name
  data:
    - secretKey: OAUTH2_PROXY_CLIENT_ID
      remoteRef:
        key: "pdla7u4t4izfeig63rcjuzuijy/username"
    - secretKey: OAUTH2_PROXY_CLIENT_SECRET
      remoteRef:
        key: "pdla7u4t4izfeig63rcjuzuijy/credential"
    - secretKey: OAUTH2_PROXY_COOKIE_SECRET
      remoteRef:
        key: "pdla7u4t4izfeig63rcjuzuijy/cookie"
