# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/common-5.0.1/charts/library/common/values.schema.json
# https://bjw-s-labs.github.io/helm-charts/docs/app-template/

defaultPodOptions:
  automountServiceAccountToken: false
  hostUsers: true # incompatible with RWX
  securityContext:
    fsGroup: 65534
    fsGroupChangePolicy: OnRootMismatch
    runAsGroup: 65534
    runAsNonRoot: true
    runAsUser: 65534
    seccompProfile:
      type: RuntimeDefault

controllers:
  app:
    enabled: true
    type: statefulset
    containers:
      app:
        image:
          repository: "docker.io/deluan/navidrome"
          tag: "0.63.2@sha256:9012939114fbb1bb641b81cf96dec5ded15f0aafefe8d47a511d7cb919658e40"
        securityContext: &sc
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
          readOnlyRootFilesystem: true
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            memory: 512Mi
        env:
          ND_BASEURL: "https://music.${DOMAIN_INTERNAL}"
          ND_CACHEFOLDER: "/tmp"
          ND_DATAFOLDER: "/data"
          ND_ENABLEGRAVATAR: "true"
          ND_ENABLEUSEREDITING: "false"
          ND_ENFORCENONROOTUSER: "true"
          ND_EXTAUTH_TRUSTEDSOURCES: "10.244.0.0/16"
          ND_EXTAUTH_USERHEADER: "X-Forwarded-User"
          ND_LOGLEVEL: "DEBUG"
          ND_MUSICFOLDER: "/mnt/music"
          ND_PROMETHEUS_ENABLED: "true"
          ND_REVERSEPROXY_WHITELIST: "10.244.0.0/16"
          TZ: ${TIMEZONE}
  auth:
    enabled: true
    containers:
      app:
        image:
          repository: "quay.io/oauth2-proxy/oauth2-proxy"
          tag: "v7.15.3@sha256:a6d60e44288b954ff1a11ed438d1196a2c3a56c64d42f7b22d5846789e5bf614"
        securityContext: *sc
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            memory: 128Mi
        envFrom:
          - secretRef:
              name: navidrome-oidc
        env:
          OAUTH2_PROXY_ALLOWED_GROUPS: "media_all,media_music"
          OAUTH2_PROXY_CODE_CHALLENGE_METHOD: S256
          OAUTH2_PROXY_COOKIE_SECURE: "true"
          OAUTH2_PROXY_EMAIL_DOMAINS: "huggins.io"
          OAUTH2_PROXY_HTTP_ADDRESS: "0.0.0.0:4180"
          OAUTH2_PROXY_INSECURE_OIDC_ALLOW_UNVERIFIED_EMAIL: "true"
          OAUTH2_PROXY_OIDC_ISSUER_URL: "https://${SUBDOMAIN_IDP}.${DOMAIN_INTERNAL}"
          OAUTH2_PROXY_PASS_USER_HEADERS: "true"
          OAUTH2_PROXY_PROVIDER: oidc
          OAUTH2_PROXY_REVERSE_PROXY: "true"
          OAUTH2_PROXY_SCOPE: "openid email profile groups"
          OAUTH2_PROXY_SET_XAUTHREQUEST: "true"
          OAUTH2_PROXY_UPSTREAMS: "http://navidrome-app.media.svc.cluster.internal:4533"

service:
  app:
    controller: app
    ports:
      http:
        port: 4533
  auth:
    controller: auth
    ports:
      http:
        port: 4180

route:
  app:
    hostnames:
      - "music.${DOMAIN_INTERNAL}"
    parentRefs:
      - name: domain-internal
        namespace: gateway-system
        sectionName: default
    rules:
      - matches:
          - path:
              type: PathPrefix
              value: "/rest"
        backendRefs:
          - identifier: app
            port: http
      - matches:
          - path:
              type: PathPrefix
              value: "/oauth2"
        backendRefs:
          - identifier: auth
            port: http
      - backendRefs:
          - identifier: auth
            port: http

persistence:
  data:
    accessMode: ReadWriteOnce
    size: 10Gi
    storageClass: longhorn
    type: persistentVolumeClaim
    advancedMounts:
      app:
        app:
          - path: "/data"
  music:
    existingClaim: files-music
    advancedMounts:
      app:
        app:
          - path: "/mnt/music"
            readOnly: true
  tmp:
    type: emptyDir
