version: "3"
services:
  ui_homer:
    image: b4bz/homer
    container_name: ui_homer
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/kjhuggins/homelab/ui_homer/data/:/www/assets/
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ui_homer.rule=PathPrefix(`/homer`)"