# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/refs/heads/main/external-secrets.io/externalsecret_v1.json

apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name golink-ts-auth
  namespace: default
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: kv2
  target:
    name: *name
  data:
    - secretKey: "TS_AUTHKEY"
      remoteRef:
        decodingStrategy: Base64
        key: "clusters-mini-golink-tailscale-authkey"
