# Compose file for the Portainer Agent
  
version: "3.9"
services:
  portainer_agent:
    image: "portainer/agent:2.16.2"
    container_name: "portainer_agent"
    restart: unless-stopped
    ports:
      - "9001:9001"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "/etc/localtime:/etc/localtime:ro"
      - "/var/lib/docker/volumes:/var/lib/docker/volumes"
