# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/app-template-3.7.3/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json

apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &name blocky
spec:
  interval: 1h
  releaseName: *name
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: &retries 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: *retries
  dependsOn:
    - name: redis
      namespace: cache
  valuesFrom:
    - kind: ConfigMap
      name: blocky-chart-values
