global:
  checkNewVersion: true

api:
  insecure: true
  dashboard: true

# enable ping so the `traefik healthcheck` works
ping: {}

providers:
  docker:
    exposedByDefault: false
    watch: true
    network: traefik-external
  file:
    fileName: /etc/traefik/traefik.yaml
    watch: true

entryPoints:
  web:
    address: :80
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true
  websecure:
    address: :443
  wireguard:
    address: :51820/udp
  mssql:
    address: :1433/tcp

serversTransport:
  insecureSkipVerify: true

certificatesResolvers:
  cloudflare:
    acme:
      storage: acme.json
      dnsChallenge:
        provider: cloudflare
        resolvers:
          - "1.1.1.1:53"
          - "1.0.0.1:53"
