# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/refs/heads/main/source.toolkit.fluxcd.io/ocirepository_v1beta2.json

apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: controlplaneio-fluxcd
spec:
  interval: 99h
  url: "oci://ghcr.io/controlplaneio-fluxcd/charts/flux-operator"
  ref:
    tag: 0.48.0
    digest: "sha256:8feb57a9af903333443e0024916f4cd65ec9df05402463daa3880863249b903d"
