# yaml-language-server: $schema=https://json.schemastore.org/kustomization

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - "./helmrelease.yaml"
  - "./resources/servicemonitor.yaml"
configMapGenerator:
  - name: blocky
    files:
      - "./resources/config.yaml"
configurations:
  - "./configuration-configmap.yaml"
