apiVersion: "cilium.io/v2alpha1"
kind: CiliumLoadBalancerIPPool
metadata:
  name: hyperlab-ingress
  namespace: kube-system
spec:
  blocks:
    - cidr: "10.0.1.10/32"
  serviceSelector:
    matchLabels:
      kube.huggins.io/ip-pool: ingress
---
apiVersion: "cilium.io/v2alpha1"
kind: CiliumLoadBalancerIPPool
metadata:
  name: hyperlab-dns
  namespace: kube-system
spec:
  blocks:
    - cidr: "10.0.1.40/32"
    - cidr: "10.0.1.50/32"
  serviceSelector:
    matchLabels:
      kube.huggins.io/ip-pool: dns
