# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json

apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name operator-oauth
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: op
  target:
    name: *name
  data:
    - secretKey: client_id
      remoteRef:
        key: "baa5v4tweychz64z2q3l2dfvea/username"
    - secretKey: client_secret
      remoteRef:
        key: "baa5v4tweychz64z2q3l2dfvea/credential"
