# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/refs/heads/main/external-secrets.io/externalsecret_v1beta1.json

apiVersion: "external-secrets.io/v1beta1"
kind: ExternalSecret
metadata:
  name: &name "golink-ts-auth"
  namespace: default
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: &source "bitwarden-secrets"
  target:
    name: *name
  data:
    - secretKey: "TS_AUTHKEY"
      remoteRef:
        key: *source
        property: "2bd9cadc-6b1e-44d3-93e7-b271016be183"
