# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json

apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name sure
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: op
  target:
    name: *name
  dataFrom:
    - find:
        path: "rn2kwfctt4rdi2j77vidblnqyu/Helm Chart"
        name:
          regexp: ".+"
