# Compose file for Docker Image Update Notifier

name: "diun"
services:
  diun:
    image: "ghcr.io/crazy-max/diun:4.23.1"
    container_name: "diun"
    restart: "unless-stopped"
    logging:
      driver: "local"
      options:
        max-file: "3"
        max-size: "5m"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "${PATH_PARENT}/homelab-data/diun-${DOCKER_HOSTNAME}/:/data/"
    environment:
      - "TZ=America/Chicago"
      - "LOG_LEVEL=info"
      - "LOG_JSON=false"
      - "DIUN_PROVIDERS_DOCKER=true"
      - "DIUN_PROVIDERS_DOCKER_WATCHBYDEFAULT=true"
      - "DIUN_WATCH_SCHEDULE=0 17 * * 6"
      - "DIUN_NOTIF_DISCORD_WEBHOOKURL=${DISCORD_WEBHOOK}"
      - "DIUN_NOTIF_DISCORD_RENDERFIELDS=true"
