# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json

apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name cloudflare-api-key
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: op
  target:
    name: *name
  data:
    - secretKey: api-key
      remoteRef:
        key: "off2m34temcqmvbaructnaytiu/dns-api-token"
