# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/refs/heads/main/tuppr.home-operations.com/kubernetesupgrade_v1alpha1.json

apiVersion: tuppr.home-operations.com/v1alpha1
kind: KubernetesUpgrade
metadata:
  name: mini
spec:
  kubernetes:
    version: v1.36.0
  maintenance:
    windows:
      - start: "0 7 * * 6"
        duration: "1h"
        timezone: "America/Chicago"
