apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &name mealie-postgres
  namespace: default
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: database-secrets
  target:
    name: *name
  data:
    - secretKey: POSTGRES_SERVER
      remoteRef:
        key: &ppa postgres-pguser-mealie
        property: host
    - secretKey: POSTGRES_DB
      remoteRef:
        key: *ppa
        property: dbname
    - secretKey: POSTGRES_USER
      remoteRef:
        key: *ppa
        property: user
    - secretKey: POSTGRES_PORT
      remoteRef:
        key: *ppa
        property: port
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: *ppa
        property: password
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &name mealie-misc
  namespace: default
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: &source bitwarden-secrets
  target:
    name: *name
  data:
    - secretKey: OIDC_CLIENT_SECRET
      remoteRef:
        key: *source
        property: f625cc42-8350-44d8-ac30-b23500336eed
