# Compose file for AdGuard Home Sync

name: "adguard_home_sync"
services:
  adguard_home_sync:
    image: "ghcr.io/bakito/adguardhome-sync:v0.4.14"
    container_name: "adguard_home_sync"
    restart: unless-stopped
    command: "run --config /config/config.yaml"
    logging:
      driver: "local"
      options:
        max-file: "3"
        max-size: "5m"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "${PATH_PARENT}/homelab-git/docker/adguard_home_sync/config.yaml:/config/config.yaml"
    environment:
      - "RUNONSTART=false"
      - "ORIGIN_URL=http://${ORIGIN_ADDRESS}"
      - "ORIGIN_PASSWORD=${PASSWORD}"
      - "REPLICA_URL=http://${REPLICA_ADDRESS}"
      - "REPLICA_PASSWORD=${PASSWORD}"
