apiVersion: tailscale.com/v1alpha1
kind: Connector
metadata:
  name: hyperlab-exit
spec:
  exitNode: true
  hostname: hyperlab-exit
  subnetRouter:
    advertiseRoutes:
      - "10.0.1.10/32"
      - "10.0.1.40/32"
      - "10.0.1.50/32"
