installCRDs: true

operatorConfig:
  defaultTags:
    - "tag:k8s-operator"

  hostname: hyperlab

  securityContext:
    allowPrivilegeEscalation: false
    capabilities:
      add:
        - NET_ADMIN
      drop:
        - ALL
    seccompProfile:
      type: RuntimeDefault
