# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/refs/heads/main/monitoring.coreos.com/servicemonitor_v1.json

apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kubewarden-controller-metrics
  namespace: security
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: kubewarden-controller
  namespaceSelector:
    matchNames:
      - security
  endpoints:
    - port: metrics
      interval: 30s
      honorLabels: true
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/refs/heads/main/monitoring.coreos.com/servicemonitor_v1.json

apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kubewarden-policy-metrics
  namespace: security
spec:
  selector:
    matchLabels:
      app: kubewarden-policy-server-default
  namespaceSelector:
    matchNames:
      - security
  endpoints:
    - port: metrics
      interval: 30s
      honorLabels: true
