auditScanner:
  enable: true
  policyReporter: true
  parallelNamespaces: 1
  parallelResources: 25
  parallelPolicies: 4
policy-reporter:
  ui:
    enabled: false
policyServer:
  requests:
    cpu: 10m
    memory: 128Mi
  limits:
    cpu: ~
    memory: 512Mi
resources:
  controller:
    requests:
      cpu: 200m
      memory: 96Mi
    limits:
      cpu: ~
      memory: 128Mi
  auditScanner:
    requests:
      cpu: 200m
      memory: 256Mi
    limits:
      cpu: ~
      memory: 256Mi
replicas: 1
