# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/helmrelease-helm-v2.json

apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app policy-reporter
  namespace: &ns kyverno-system
spec:
  interval: 1h
  releaseName: *app
  chart:
    spec:
      chart: *app
      version: 3.7.2
      sourceRef:
        kind: HelmRepository
        name: policy-reporter
        namespace: *ns
  install:
    crds: CreateReplace
    remediation:
      retries: &retries 3
  upgrade:
    cleanupOnFail: true
    crds: CreateReplace
    remediation:
      retries: *retries
  valuesFrom:
    - kind: ConfigMap
      name: policy-reporter-chart-values
