# https://github.com/kyverno/policy-reporter/blob/main/charts/policy-reporter/values.yaml

podLabels:
  kube.huggins.io/cache-db: "2"

podSecurityContext:
  fsGroup: 65532

resources:
  requests:
    cpu: 10m
    memory: 32Mi
  limits:
    cpu: 100m
    memory: 64Mi

securityContext:
  runAsUser: 65532
  runAsNonRoot: true
  privileged: false
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  capabilities:
    drop:
      - ALL

metrics:
  enabled: true

workers: 1

# TODO: integrate with FOC

redis:
  enabled: true
  address: "valkey.cache.svc.cluster.local:6379"
  database: 2

ui:
  enabled: false
