# https://github.com/external-secrets/external-secrets/blob/main/deploy/charts/external-secrets/values.yaml
# yaml-language-server: $schema=https://raw.githubusercontent.com/external-secrets/external-secrets/refs/heads/main/deploy/charts/external-secrets/values.schema.json

serviceMonitor:
  enabled: true

hostNetwork: false
hostUsers: false

resources:
  requests:
    cpu: 10m
    memory: 128Mi
  limits:
    memory: 256Mi

webhook:
  hostNetwork: false
  hostUsers: false
  resources:
    requests:
      cpu: 10m
      memory: 96Mi
    limits:
      memory: 96Mi

certController:
  hostNetwork: false
  hostUsers: false
  resources:
    requests:
      cpu: 10m
      memory: 96Mi
    limits:
      memory: 96Mi
