# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &name ingress-nginx
  namespace: network
spec:
  interval: 10m
  releaseName: *name
  chart:
    spec:
      chart: *name
      version: 4.11.3
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: flux-system
  install:
    remediation:
      retries: &retries 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: *retries
  values:
    controller:
      ingressClassResource:
        default: true
    service:
      annotations:
        kube.huggins.io/ingress: "true"
