# https://docs.cilium.io/en/stable/
# yaml-language-server: $schema=https://raw.githubusercontent.com/cilium/cilium/refs/heads/main/install/kubernetes/cilium/values.schema.json
# Configured for single-node Talos cluster. Multi-node clusters require additional configuration.

cgroup:
  autoMount:
    enabled: false
  hostRoot: "/sys/fs/cgroup"

encryption:
  enabled: true # TODO: should we enable encryption for single-node clusters?
  type: wireguard
  nodeEncryption: true

envoy:
  enabled: true
  securityContext:
    capabilities:
      keepCapNetBindService: true

hubble:
  relay:
    enabled: true
  ui:
    enabled: true

ipam:
  mode: kubernetes # TODO: should we deviate from default?

k8sServiceHost: localhost
k8sServicePort: 7445
kubeProxyReplacement: true

l2announcements:
  enabled: true

loadBalancer:
  algorithm: maglev

nodeIPAM:
  enabled: true

operator:
  prometheus:
    enabled: false
    serviceMonitor:
      enabled: false
      interval: 30s
  replicas: 1 # how can I handle this with both helmfile and flux?

prometheus:
  enabled: false
  serviceMonitor:
    enabled: false
    interval: 30s

securityContext:
  capabilities:
    ciliumAgent:
      - CHOWN
      - DAC_OVERRIDE
      - FOWNER
      - IPC_LOCK
      - KILL
      - NET_ADMIN
      - NET_BIND_SERVICE
      - NET_RAW
      - SETGID
      - SETUID
      - SYS_ADMIN
      - SYS_RESOURCE
    cleanCiliumState:
      - NET_ADMIN
      - SYS_ADMIN
      - SYS_RESOURCE

socketLB:
  hostNamespaceOnly: true
