apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: tailscale-operator-secret
  namespace: tailscale
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: &source bitwarden-secrets
  target:
    name: operator-oauth
  data:
    - secretKey: client_id
      remoteRef:
        key: *source
        property: 24ac8ab7-3d30-4bec-bfcd-b1f5002032a9
    - secretKey: client_secret
      remoteRef:
        key: *source
        property: 4ff360bd-ef0b-4f51-9132-b1f5002069e4
