# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/policies.kyverno.io/validatingpolicy_v1.json

apiVersion: policies.kyverno.io/v1
kind: ValidatingPolicy
metadata:
  annotations:
    policies.kyverno.io/description: Requires all containers to have a read-only root filesystem.
    policies.kyverno.io/severity: medium
    policies.kyverno.io/title: Require read-only root filesystem.
  name: require-readonly-rootfs
spec:
  autogen:
    validatingAdmissionPolicy:
      enabled: true
    podControllers:
      controllers:
        - cronjobs
        - deployments
        - jobs
        - statefulsets
  matchConstraints:
    resourceRules:
      - apiGroups:
          - ""
        apiVersions:
          - v1
        operations:
          - CREATE
          - UPDATE
        resources:
          - pods
  validationActions:
    - Audit
  variables:
    - name: allContainers
      expression: "object.spec.containers + object.spec.?initContainers.orValue([])"
  validations:
    - expression: "variables.allContainers.all(c, c.?securityContext.?readOnlyRootFilesystem.orValue(false) == true)"
      message: Container must have a read-only root filesystem.
