# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/refs/heads/main/kyverno.io/policyexception_v2.json

apiVersion: kyverno.io/v2
kind: PolicyException
metadata:
  name: kube-system-exception
  namespace: &ns kube-system
spec:
  exceptions:
    - policyName: disallow-capabilities-strict
      ruleNames:
        - autogen-adding-capabilities-strict
        - autogen-require-drop-all
  match:
    any:
      - resources:
          namespaces:
            - *ns
          # TODO: PolicyExceptions for shared resources
