apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: hyperlab-internal-domain
  namespace: cert-manager
spec:
  secretName: hyperlab-internal-domain-tls
  isCA: false

  dnsNames:
    - ${DOMAIN_PRIVATE}
    - "*${DOMAIN_PRIVATE}"

  issuerRef:
    name: letsencrypt-staging
    kind: Issuer
