apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
  namespace: cert-manager
spec:
  acme:
    email: ${EMAIL_CONTACT}
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-staging-account-key
    solvers:
      - dns01:
          cloudflare:
            email: ${EMAIL_PRIVATE}
            apiTokenSecretRef:
              name: cloudflare-api-key
              key: api-token
        selector:
          dnsZones:
            - ${DOMAIN_PRIVATE}
