apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &name cloudflare-api-key
  namespace: cert-manager
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: &source bitwarden-secrets
  target:
    name: *name
  data:
    - secretKey: api-key
      remoteRef:
        key: *source
        property: 862a2ee4-f2dd-4a6f-a26b-b20a00138cb0
