# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/policies.kyverno.io/validatingpolicy_v1.json

apiVersion: policies.kyverno.io/v1
kind: ValidatingPolicy
metadata:
  annotations:
    policies.kyverno.io/description: Requires all container images to specify a tag other than 'latest'.
    policies.kyverno.io/severity: high
    policies.kyverno.io/title: Require explicit image tags.
  name: require-explicit-image-tags
spec:
  autogen:
    validatingAdmissionPolicy:
      enabled: true
    podControllers:
      controllers:
        - cronjobs
        - deployments
        - jobs
        - statefulsets
  matchConstraints:
    resourceRules:
      - apiGroups:
          - ""
        apiVersions:
          - v1
        operations:
          - CREATE
          - UPDATE
        resources:
          - pods
  validationActions:
    - Audit
  variables:
    - name: allContainers
      expression: "object.spec.containers + object.spec.?initContainers.orValue([])"
  validations:
    - expression: >-
        variables.allContainers.all(c,
          !c.image.endsWith(':latest') &&
          c.image.contains(':') &&
          !c.image.endsWith(':'))
      message: "Containers must not use image tag 'latest'."
